/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_0c561120 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/jvmddidfxabdbtiscdop/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0c561120").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_0c561120").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0c561120").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0c561120").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_0c561120").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0c561120").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix. Supabase silently caps single
// select() calls at 1000 rows, so once the catalog crosses ~1000 products
// (or 1000 categories, etc.) results were being truncated. We page through
// the table 1000 rows at a time until we hit the end.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const PAGE = 1000;
  const out: any[] = [];
  let from = 0;
  // Loop until a page returns less than PAGE rows (= last page).
  // Hard upper bound of 100 pages (= 100k rows) as a safety net so a buggy
  // prefix can never spin forever.
  for (let i = 0; i < 100; i++) {
    const { data, error } = await supabase
      .from("kv_store_0c561120")
      .select("value")
      .like("key", prefix + "%")
      .order("key", { ascending: true })
      .range(from, from + PAGE - 1);
    if (error) {
      throw new Error(error.message);
    }
    if (!data || data.length === 0) break;
    for (const d of data) out.push(d.value);
    if (data.length < PAGE) break;
    from += PAGE;
  }
  return out;
};